update=12/15/2018 6:24:10 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Transistor
LibName2=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Transformer
LibName3=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Symbol
LibName4=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Switch
LibName5=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Sensor
LibName6=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Resistor
LibName7=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Relay
LibName8=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_power
LibName9=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Potentiometer
LibName10=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Optoisolator
LibName11=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Module
LibName12=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Misc
LibName13=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Inductor_Variable
LibName14=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Inductor_Fixed
LibName15=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_RF
LibName16=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Power
LibName17=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Interface
LibName18=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Digital
LibName19=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Data_Conversion
LibName20=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Analog
LibName21=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Diode
LibName22=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Crystal
LibName23=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Connector
LibName24=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Circuit_Protection
LibName25=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Capacitor_Polarized
LibName26=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Capacitor
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
